version: '3.4'

services:
  n-tier.api:
    image: ${DOCKER_REGISTRY-}ntierapi
    build:
      context: .
      dockerfile: src/N-Tier.API/Dockerfile

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      - "postgres"
    ports:
      - 15432:80
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      # POSTGRES_HOST: "postgres"
      # POSTGRES_PORT: "5432"
      # POSTGRES_DB: "*"
    restart: unless-stopped

volumes:
  postgres-data:
